POST http://localhost:8180/realms/Bandit%20Games/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id = <client> &
client_secret = <secret> &
username = <client> &
password = <password> &
grant_type = password &
scope = openid

//saving the access token
> {%
    client.global.set("access_token", response.body.access_token);
    console.log("Access Token:", client.global.get("access_token"));
%}

###

POST http://localhost:8041/api/v1/chat/query
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "query": "Hello chatbot!"
}